# -*- coding: utf-8 -*-
"""
armintesisat.com veri katmanı.

⛔ Üretilen HTML'i ELLE DÜZENLEME — build.py her çalıştığında üzerine yazar.
   Metin/veri değişikliği BURAYA yapılır, sonra:  python3 _src/build.py && python3 _src/denetim.py
"""

# ── Firma ───────────────────────────────────────────────────────────────────
# ⛔ Uydurma bilgi YOK. Adres sitede hiç yayınlanmamıştı → yazılmıyor (hizmet bölgesi işletmesi).
SITE = {
    "marka":      "Armin Tesisat",
    "alan":       "https://www.armintesisat.com",
    "cname":      "www.armintesisat.com",
    "tel_goster": "0532 247 21 59",
    "tel_link":   "+905322472159",
    "wa":         "905322472159",
    "bolge":      "İstanbul Avrupa Yakası",
    "kurulus":    "2023",          # eski sitenin telif satırından
}

# Google Ads (hesap etiketi zaten canlıydı). "tel"/"wa" = dönüşüm snippet'indeki
# send_to ETİKETİ (AW-…/ sonrasındaki kısım). Boşken tıklama dinleyicisi hiçbir şey göndermez.
ADS = {
    "etiket": "AW-18029618703",          # dönüşümlerin açıldığı hesap (2026-10-03)
    "ek":     ["AW-17846613936"],         # önceki etiket, yanında yüklenmeye devam eder
    "tel":    "",
    "wa":     "",
}

# ✅ ONAYLI — kullanıcı 2026-10-03'te seçti.
ONAYLI = {
    "yirmidort": "7/24 hizmet",
    "varis":     "ortalama 30 dakika",
}

# ⛔ KALDIRILDI (kullanıcı onaylamadı, 2026-10-03). denetim.py HTML'de görürse HATA verir.
TEYITSIZ = ["10+ yıl", "10 yıl", "1000+", "%100", "memnun müşteri", "yıllık deneyim"]

# ⛔ Üstünlük iddiası (Ticari Reklam Yönetmeliği ispat ister) → denetim HATA.
YASAK_IDDIA = ["en iyi", "en ucuz", "lider", "bir numara", "1 numara", "rakipsiz",
               "en kaliteli", "en hızlı", "yetkili servisiyiz", "yetkili servis olarak"]


# ── Türkçe ek tablosu ───────────────────────────────────────────────────────
# ⛔ Kodda "{ad}'da" gibi elle ek YAZMA → build.ek(i, "loc|dat|gen|abl")
#                 loc(-de)  dat(-e)  gen(-in)  abl(-den)
ILCE_EK = {
    "arnavutkoy":    ("'de",  "'e",   "'ün",   "'den"),
    "avcilar":       ("'da",  "'a",   "'ın",   "'dan"),
    "bagcilar":      ("'da",  "'a",   "'ın",   "'dan"),
    "bahcelievler":  ("'de",  "'e",   "'in",   "'den"),
    "bakirkoy":      ("'de",  "'e",   "'ün",   "'den"),
    "basaksehir":    ("'de",  "'e",   "'in",   "'den"),
    "bayrampasa":    ("'da",  "'ya",  "'nın",  "'dan"),
    "besiktas":      ("'ta",  "'a",   "'ın",   "'tan"),
    "beylikduzu":    ("'nde", "'ne",  "'nün",  "'nden"),
    "beyoglu":       ("'nda", "'na",  "'nun",  "'ndan"),
    "buyukcekmece":  ("'de",  "'ye",  "'nin",  "'den"),
    "catalca":       ("'da",  "'ya",  "'nın",  "'dan"),
    "esenler":       ("'de",  "'e",   "'in",   "'den"),
    "esenyurt":      ("'ta",  "'a",   "'un",   "'tan"),
    "eyupsultan":    ("'da",  "'a",   "'ın",   "'dan"),
    "fatih":         ("'te",  "'e",   "'in",   "'ten"),
    "gaziosmanpasa": ("'da",  "'ya",  "'nın",  "'dan"),
    "gungoren":      ("'de",  "'e",   "'in",   "'den"),
    "kagithane":     ("'de",  "'ye",  "'nin",  "'den"),
    "kucukcekmece":  ("'de",  "'ye",  "'nin",  "'den"),
    "sariyer":       ("'de",  "'e",   "'in",   "'den"),
    "silivri":       ("'de",  "'ye",  "'nin",  "'den"),
    "sultangazi":    ("'de",  "'ye",  "'nin",  "'den"),
    "sisli":         ("'de",  "'ye",  "'nin",  "'den"),
    "zeytinburnu":   ("'nda", "'na",  "'nun",  "'ndan"),
}


# ── İlçeler (Avrupa yakası, 25) ─────────────────────────────────────────────
# Metin bu alanlardan türetilir; amaç ilçe adını değiştirip 125 kopya üretmek değil.
#   yapi  : yapı stoğu            boru  : temiz su tesisatı tarafı
#   gider : pis su / gider tarafı isinma: ısınma düzeni (kombi/petek sayfaları)
#   saha  : ekibin sahada dikkat ettiği şey
#   mahalle: gerçek mahalle adları — ⛔ sayfa AÇILMAZ, sadece metinde geçer
# Hepsi TAM CÜMLE; şablon sadece art arda dizer (ek hatası riski yok).
ILCELER = [
 {"ad":"Arnavutköy","slug":"arnavutkoy",
  "komsu":["basaksehir","eyupsultan","catalca","esenyurt","sultangazi"],
  "mahalle":["Hadımköy","Taşoluk","Bolluca","Haraççı","Boğazköy","Ömerli"],
  "yapi":"Arnavutköy'de eski köy dokusundan kalan müstakil evlerle Taşoluk ve Boğazköy tarafındaki yeni toplu konutlar yan yana duruyor.",
  "boru":"Müstakil evlerde tesisat çoğu zaman sonradan eklenmiş parçalardan oluşuyor; aynı hatta galvaniz, plastik ve bakır bir arada çıkabiliyor.",
  "gider":"Bahçeli evlerde dış gider hattı uzun olduğu için tıkanıklık çoğu zaman evin içinde değil, bahçedeki rögar ile ev arasındaki bölümde çıkıyor.",
  "isinma":"Yeni konutlarda kombi standart; müstakil evlerde ise kombiye sonradan geçilmiş, eski kalorifer peteklerinin korunduğu sistemler sık görülüyor.",
  "saha":"İlçe çok geniş olduğu için adres tarifini telefonda netleştiriyor, Hadımköy sanayi tarafıyla konut tarafını ayrı planlıyoruz."},
 {"ad":"Avcılar","slug":"avcilar",
  "komsu":["esenyurt","beylikduzu","kucukcekmece","basaksehir"],
  "mahalle":["Ambarlı","Denizköşkler","Merkez","Üniversite","Cihangir","Tahtakale"],
  "yapi":"Avcılar'ın konut stoğunun büyük kısmı 1980'lerle 2000'ler arasında yapılmış orta katlı apartmanlardan oluşuyor.",
  "boru":"Bu yaştaki binaların bir kısmında galvaniz kolon hâlâ yerinde; içten paslanan galvaniz hem basınç düşüklüğü hem de rakor noktalarında sızıntı yapıyor.",
  "gider":"Öğrenci evlerinin yoğun olduğu Üniversite ve Cihangir tarafında mutfak giderleri yağ birikimiyle sık tıkanıyor.",
  "isinma":"Apartmanların çoğu doğalgaza geçişte kat kaloriferinden bireysel kombiye dönmüş; eski petek hatları yeni kombiye bağlandığı için çamur birikimi sık.",
  "saha":"Akşam saatlerinde gelen çağrılar fazla olduğu için Avcılar'da mesai sonrasını da planımıza katıyoruz."},
 {"ad":"Bağcılar","slug":"bagcilar",
  "komsu":["bahcelievler","gungoren","esenler","kucukcekmece","basaksehir"],
  "mahalle":["Güneşli","Kirazlı","Yıldıztepe","Demirkapı","Mahmutbey","Yenimahalle"],
  "yapi":"Bağcılar yoğun apartman adalarından oluşuyor; birçok binanın zemin katı atölye ya da dükkâna çevrilmiş durumda.",
  "boru":"Zemin katı iş yeri olan binalarda tesisat sonradan bölündüğü için ana vana ile daire vanaları arasında beklenmedik bağlantılar çıkabiliyor.",
  "gider":"Atölye ve dükkân giderleriyle konut giderlerinin aynı ana hatta bağlandığı binalarda tıkanıklık genelde en alt kattan başlıyor.",
  "isinma":"Daire başı kombi yaygın; eski binalarda sonradan yapılan petek tesisatı ince borularla çekildiği için tortu hızlı birikiyor.",
  "saha":"Güneşli ve Mahmutbey tarafındaki sanayi yoğunluğu nedeniyle mesai dışı ve hafta sonu çağrıları da karşılıyoruz."},
 {"ad":"Bahçelievler","slug":"bahcelievler",
  "komsu":["bagcilar","bakirkoy","gungoren","kucukcekmece"],
  "mahalle":["Şirinevler","Yenibosna","Soğanlı","Kocasinan","Siyavuşpaşa","Zafer"],
  "yapi":"Bahçelievler'de 1985–2005 arasında yapılmış, birbirine yakın apartman blokları çoğunlukta.",
  "boru":"Bu dönemin binalarında kolon hatları duvar içinden geçtiği için kaçak çoğu zaman alt kattaki komşunun tavanında leke olarak fark ediliyor.",
  "gider":"Bina ana gider hattı ortak olduğu için tek dairedeki tıkanıklık bazen bütün kolonu etkiliyor; önce sorunun daire içinde mi ortak hatta mı olduğunu ayırıyoruz.",
  "isinma":"Bireysel kombi yaygın; Şirinevler ve Yenibosna'daki eski binalarda petekler kombiden yaşlı olduğu için alt kısımları çabuk soğuyor.",
  "saha":"Apartman görevlisi veya yöneticiyle konuşup bina ana vanasının ve ortak hattın yerini baştan öğreniyoruz."},
 {"ad":"Bakırköy","slug":"bakirkoy",
  "komsu":["bahcelievler","zeytinburnu","gungoren","kucukcekmece"],
  "mahalle":["Ataköy","Yeşilköy","Florya","Yeşilyurt","Zeytinlik","Cevizlik"],
  "yapi":"Bakırköy'de Ataköy blokları, Yeşilköy–Florya hattındaki eski bahçeli evler ve merkezdeki köklü apartmanlar bir arada.",
  "boru":"Ataköy'ün ilk etap bloklarında ve merkezdeki eski apartmanlarda tesisatın önemli kısmı onlarca yıllık; vana ve rakor yenilemesi sık yapılan iş.",
  "gider":"Sahile yakın düşük kotlu binalarda yoğun yağışta bodrum giderlerinin geri tepmesi görülebiliyor.",
  "isinma":"Ataköy'de merkezi sistemden bireysel kombiye geçmiş daireler ile hâlâ merkezi ısınan bloklar bir arada; petek temizliğinde önce sistemin hangisi olduğunu ayırıyoruz.",
  "saha":"Site bloklarında yönetim ve güvenlik prosedürüne uyarak giriyor, ekipmanı bloklar arasında elde taşıyoruz."},
 {"ad":"Başakşehir","slug":"basaksehir",
  "komsu":["kucukcekmece","esenyurt","arnavutkoy","sultangazi","bagcilar","esenler"],
  "mahalle":["İkitelli","Kayaşehir","Ziya Gökalp","Başak","Altınşehir","Bahçeşehir"],
  "yapi":"Başakşehir'de Bahçeşehir ve Kayaşehir'deki yeni siteler ile İkitelli tarafındaki sanayi bölgesi bir arada.",
  "boru":"Yeni sitelerde tesisat genellikle plastik esaslı ve kollektörlü; arıza çoğunlukla kollektör vanalarında ve ankastre bağlantılarda çıkıyor.",
  "gider":"Yeni binalarda gider hatları sağlam ama inşaat artığı, derz dolgusu ve silikon parçaları ilk yıllarda tıkanıklığa yol açabiliyor.",
  "isinma":"Sitelerin çoğunda yerden ısıtma ya da panel petek ile bireysel kombi var; yerden ısıtmalı dairelerde kollektör ve devre dengesine ayrıca bakıyoruz.",
  "saha":"Kapalı sitelerde güvenliğe ad ve plaka bilgisini önceden bildirip girişi hızlandırıyoruz."},
 {"ad":"Bayrampaşa","slug":"bayrampasa",
  "komsu":["esenler","gaziosmanpasa","eyupsultan","fatih","zeytinburnu"],
  "mahalle":["Yıldırım","Kartaltepe","Altıntepsi","Muratpaşa","Terazidere","Vatan"],
  "yapi":"Bayrampaşa'da konutlarla iş yerleri iç içe; özellikle hal ve toptancılar çevresinde zemin katlar ticari kullanımda.",
  "boru":"Eski apartmanlarda kat çıkışları ve dükkân bölmeleri yüzünden tesisat parça parça yenilenmiş; farklı malzemelerin birleştiği noktalar sızıntıya açık.",
  "gider":"İş yeri giderlerinin yoğun kullanıldığı binalarda ortak hat, daire hatlarından önce tıkanıyor.",
  "isinma":"Apartmanlarda daire başı kombi yaygın, iş yerlerinde ise küçük kapasiteli kombiler ve elektrikli ısıtıcılar bir arada kullanılıyor.",
  "saha":"Hal çevresinde iş akışını aksatmamak için çalışma saatini iş yeri sahibiyle birlikte belirliyoruz."},
 {"ad":"Beşiktaş","slug":"besiktas",
  "komsu":["sisli","sariyer","beyoglu"],
  "mahalle":["Ortaköy","Bebek","Etiler","Levent","Arnavutköy","Gayrettepe"],
  "yapi":"Beşiktaş'ta yamaca oturan eski apartmanlar, Etiler ve Levent'teki siteler ile ofis blokları bir arada.",
  "boru":"Yamaçtaki eski binalarda kot farkı yüzünden üst katlarda basınç düşüklüğü, alt katlarda ise yüksek basınca bağlı batarya arızaları görülüyor.",
  "gider":"Eğimli parsellerde bina gideri sokak hattına uzun bir mesafeden bağlandığı için tıkanıklığın yeri kamerayla belirlenmeden kazı kararı verilmiyor.",
  "isinma":"Eski apartmanların bir kısmı hâlâ merkezi sistemle ısınıyor, yenilenen dairelerde ise bireysel kombi var.",
  "saha":"Dar ve eğimli sokaklarda araç yerini önceden ayarlıyor, gerekirse ekipmanı elle taşıyoruz."},
 {"ad":"Beylikdüzü","slug":"beylikduzu",
  "komsu":["esenyurt","avcilar","buyukcekmece"],
  "mahalle":["Cumhuriyet","Barış","Gürpınar","Yakuplu","Adnan Kahveci","Marmara"],
  "yapi":"Beylikdüzü büyük ölçüde 2005 sonrasında kurulmuş planlı site ve rezidans yerleşiminden oluşuyor.",
  "boru":"Sitelerde tesisat yeni ama ankastre; kaçak duvarın ya da şapın içinde ilerlediği için çoğu zaman ancak su faturası ya da komşu tavanındaki lekeyle fark ediliyor.",
  "gider":"Sitelerde daire hattı ile blok ortak hattı ayrı; tıkanıklığın hangisinde olduğunu ayırmak site yönetimiyle sorumluluk paylaşımını da belirliyor.",
  "isinma":"Neredeyse tüm dairelerde bireysel kombi var; ilk yıllarda yapılmış sitelerde kombiler ilk değişim yaşına geldi.",
  "saha":"Site yönetimine bilgi vererek giriyor, ortak alanı ilgilendiren durumları yönetime ayrıca raporluyoruz."},
 {"ad":"Beyoğlu","slug":"beyoglu",
  "komsu":["sisli","besiktas","kagithane","eyupsultan","fatih"],
  "mahalle":["Cihangir","Galata","Tarlabaşı","Kasımpaşa","Şişhane","Hacımimi"],
  "yapi":"Beyoğlu'nda yüz yılı aşkın taş ve kâgir binalar çoğunlukta; birçoğu sonradan dairelere ya da konaklama birimlerine bölünmüş.",
  "boru":"Eski binalarda tesisat defalarca parça parça yenilendiği için duvar içinde eski kurşun ya da galvaniz parçalar kalmış olabiliyor.",
  "gider":"Döküm gider boruları yıllar içinde içten kabuklandığı için çap daralıyor; tıkanıklık açıldıktan sonra da bu daralmayı not ediyoruz.",
  "isinma":"Bölünmüş eski binalarda daire başı küçük kombiler ve sonradan çekilmiş ince petek hatları yaygın.",
  "saha":"Dar sokak ve merdivenli girişlerde ekipmanı elle taşıyor, tarihi dokuda kırmadan çalışmayı öncelikli tutuyoruz."},
 {"ad":"Büyükçekmece","slug":"buyukcekmece",
  "komsu":["beylikduzu","esenyurt","silivri","catalca","arnavutkoy"],
  "mahalle":["Mimarsinan","Kumburgaz","Celaliye","Kamiloba","Atatürk","Türkoba"],
  "yapi":"Büyükçekmece'de sahil yazlıkları ile yıl boyu oturulan siteler yan yana; Mimarsinan ve Kumburgaz yazın kalabalıklaşıyor.",
  "boru":"Kışın boş kalan yazlıklarda donma ve uzun süre kullanılmamaktan kaynaklı conta bozulmaları sezon başında sızıntı olarak ortaya çıkıyor.",
  "gider":"Yaz nüfusuyla kullanım katlandığı için sezon başında ve ortasında gider tıkanıklığı çağrıları artıyor.",
  "isinma":"Yıl boyu oturulan sitelerde kombi standart; yazlıklarda ise kombinin uzun süre çalıştırılmaması basınç ve kireç sorunlarına yol açıyor.",
  "saha":"Mesafe uzun olduğu için Büyükçekmece'deki işleri aynı güzergâhta topluyoruz."},
 {"ad":"Çatalca","slug":"catalca",
  "komsu":["silivri","buyukcekmece","arnavutkoy"],
  "mahalle":["Ferhatpaşa","Kaleiçi","Ovayenice","Çanakça","İzzettin","Elbasan"],
  "yapi":"Çatalca'da köy yerleşimleri, müstakil evler ve tarım işletmeleri ağırlıkta.",
  "boru":"Müstakil evlerde ana hattan eve kadar olan bölüm uzun; toprak altındaki hatta oluşan kaçak bahçede ıslak bir alan olarak kendini gösteriyor.",
  "gider":"Bir kısım yerleşimde hâlâ fosseptik kullanıldığı için tıkanıklık ile fosseptik dolmasını birbirinden ayırmak gerekiyor.",
  "isinma":"Doğalgaz olmayan bölgelerde soba ve kat kaloriferi, doğalgazlı merkezde ise kombi kullanılıyor; petek temizliği her iki sistemde de yapılabiliyor.",
  "saha":"Mesafe uzun olduğu için Çatalca'ya çıkışı günün başında planlıyor, adres tarifini telefonda netleştiriyoruz."},
 {"ad":"Esenler","slug":"esenler",
  "komsu":["bagcilar","gungoren","bayrampasa","gaziosmanpasa","sultangazi","basaksehir"],
  "mahalle":["Fevziçakmak","Menderes","Oruçreis","Havaalanı","Çifte Havuzlar","Nine Hatun"],
  "yapi":"Esenler'de 1990'larda yükselen yoğun apartman dokusu ve otogar çevresindeki iş yerleri ağırlıkta.",
  "boru":"Bu dönemin apartmanlarında galvanizden plastiğe geçiş yarım kalmış; kolon eski, daire içi yeni olan binalarda bağlantı noktaları sorun çıkarıyor.",
  "gider":"Sık aralıklı binalarda bodrum katlar sokak kotunun altında kaldığı için gider geri tepmesi daha çok bodrum ve zemin katlarda görülüyor.",
  "isinma":"Daire başı kombi yaygın; eski binalarda petek hatları kombiden önce döşendiği için sistemde çamur ve hava sorunu sık.",
  "saha":"Yoğun apartman sokaklarında aracı uygun yere bırakıp ekipmanı kısa mesafe elde taşıyoruz."},
 {"ad":"Esenyurt","slug":"esenyurt",
  "komsu":["beylikduzu","avcilar","basaksehir","buyukcekmece","arnavutkoy"],
  "mahalle":["Örnek","Yenikent","Saadetdere","Balıkyolu","İnönü","Namık Kemal"],
  "yapi":"Esenyurt kısa sürede yükselmiş çok bloklu yeni konut alanlarından oluşuyor; aynı sokakta 2000'lerin başındaki apartmanlarla yeni siteler yan yana.",
  "boru":"Hızlı yapılaşma döneminin binalarında tesisat işçiliği binadan binaya çok farklı; ankastre bağlantılarda ve kollektörlerde sızıntı sık karşılaştığımız durum.",
  "gider":"Yeni bloklarda inşaat artığı ve derz dolgusu gider hatlarına kaçabiliyor; yoğun nüfuslu binalarda ortak hat da hızlı yükleniyor.",
  "isinma":"Neredeyse her dairede bireysel kombi var; yoğun kullanılan kombilerde basınç düşmesi ve sıcak su dalgalanması en sık çağrı nedeni.",
  "saha":"Esenyurt'ta çağrı yoğunluğu yüksek; mahalleyi ve blok numarasını baştan alıp ekibi en yakın noktadan yönlendiriyoruz."},
 {"ad":"Eyüpsultan","slug":"eyupsultan",
  "komsu":["gaziosmanpasa","bayrampasa","kagithane","sariyer","arnavutkoy","sultangazi","beyoglu"],
  "mahalle":["Alibeyköy","Göktürk","Rami","Nişanca","Silahtarağa","Kemerburgaz"],
  "yapi":"Eyüpsultan'da tarihi Eyüp dokusu, Alibeyköy ve Rami'nin yoğun apartmanları ile Göktürk ve Kemerburgaz'daki yeni siteler bir arada.",
  "boru":"Eski Eyüp ve Rami tarafında eski galvaniz hatlar, Göktürk tarafında ise yeni ve ankastre tesisat var; arıza tipi bölgeye göre tamamen değişiyor.",
  "gider":"Vadi ile sırt arasındaki kot farkı yüzünden alt kottaki binalarda yağışlı havalarda gider geri tepmesi görülebiliyor.",
  "isinma":"Göktürk sitelerinde yerden ısıtma ve büyük kapasiteli kombiler, eski bölgelerde ise klasik petekli kombi sistemleri yaygın.",
  "saha":"Bölgeler arası mesafe uzun olduğu için mahalleyi baştan öğrenip ekibi doğru taraftan yönlendiriyoruz."},
 {"ad":"Fatih","slug":"fatih",
  "komsu":["zeytinburnu","bayrampasa","eyupsultan","beyoglu"],
  "mahalle":["Aksaray","Balat","Fener","Çapa","Sultanahmet","Kocamustafapaşa"],
  "yapi":"Fatih tarihi yarımadanın yüzyıllık binalarından, otel ve lokanta yoğunluğundan oluşuyor.",
  "boru":"Eski binalarda tesisat duvar içinde değil çoğu zaman sonradan yüzeyden geçirilmiş; görünen ama yaşlı hatlarda rakor ve vana arızası sık.",
  "gider":"Lokanta ve otellerin yoğun olduğu bölgelerde yağ ve atık yükü yüksek, ana hatta tıkanıklık sık yaşanıyor.",
  "isinma":"Eski binalarda merkezi sistemler hâlâ kullanılıyor; daire bazında kombiye geçenlerde ise eski petekler korunmuş.",
  "saha":"Sit alanı ve dar sokaklarda kırmadan çalışmayı öncelikli tutuyor, ekipmanı elle taşıyoruz."},
 {"ad":"Gaziosmanpaşa","slug":"gaziosmanpasa",
  "komsu":["sultangazi","eyupsultan","bayrampasa","esenler"],
  "mahalle":["Karayolları","Yenidoğan","Merkez","Sarıgöl","Hürriyet","Barbaros Hayrettin"],
  "yapi":"Gaziosmanpaşa'da kentsel dönüşüm sürüyor; eski apartmanlarla yeni bloklar aynı sokakta yan yana duruyor.",
  "boru":"Dönüşüm bekleyen eski binalarda tesisat yorgun ve yenileme ertelenmiş durumda; küçük bir kaçak kısa sürede büyüyebiliyor.",
  "gider":"Eski binaların gider hatları dar çaplı; yeni bloklara göre tıkanıklık daha sık tekrarlıyor.",
  "isinma":"Yeni bloklarda yeni kombiler, eski binalarda ise uzun yıllardır bakım görmemiş kombi ve petekler yaygın.",
  "saha":"Şantiye trafiği nedeniyle aracı yaklaştıracağımız noktayı telefonda önceden konuşuyoruz."},
 {"ad":"Güngören","slug":"gungoren",
  "komsu":["bagcilar","esenler","bahcelievler","zeytinburnu","bakirkoy","bayrampasa"],
  "mahalle":["Merter","Tozkoparan","Haznedar","Gençosman","Sanayi","Akıncılar"],
  "yapi":"Güngören'de konutlar Merter çevresindeki tekstil atölyeleriyle iç içe geçmiş yoğun bir yapıya sahip.",
  "boru":"Atölyeye dönüştürülmüş katlarda tesisat sonradan değiştirildiği için ana hattan ayrılan kaçak bağlantılar ve basınç farkları görülebiliyor.",
  "gider":"Atölye kullanımı olan binalarda lif ve kumaş artığı ortak gider hattına karışabiliyor.",
  "isinma":"Konut katlarında bireysel kombi yaygın; atölye katlarında ise farklı ısıtma çözümleri bir arada kullanılıyor.",
  "saha":"Atölye yoğun sokaklarda üretimi aksatmamak için çalışma saatini iş yeriyle birlikte belirliyoruz."},
 {"ad":"Kağıthane","slug":"kagithane",
  "komsu":["sisli","eyupsultan","beyoglu","sariyer"],
  "mahalle":["Merkez","Çağlayan","Seyrantepe","Gültepe","Hamidiye","Nurtepe"],
  "yapi":"Kağıthane'de vadi tabanında ofis ve rezidans dönüşümü, yamaçlarda ise eski konut stoğu var.",
  "boru":"Yamaçtaki eski binalarda üst katlarda su basıncı düşük; hidrofor ve basınç düşürücü ayarları sık bakılan konu.",
  "gider":"Kot farkı yüksek olduğu için yamaçtaki binaların gider hatları uzun ve eğimli; tıkanıklık noktası kamerayla bulunmadan müdahale planlanmıyor.",
  "isinma":"Eski konutlarda petekli kombi sistemi yaygın; yeni rezidanslarda ise merkezi ya da bina tipi ısınma sistemleri de var.",
  "saha":"Yokuşlu sokaklarda aracın yanaşamadığı adreslere taşınabilir ekipmanla çıkıyoruz."},
 {"ad":"Küçükçekmece","slug":"kucukcekmece",
  "komsu":["avcilar","basaksehir","bagcilar","bahcelievler","bakirkoy"],
  "mahalle":["Sefaköy","Halkalı","Atakent","İnönü","Cennet","Kanarya"],
  "yapi":"Küçükçekmece'de eski Sefaköy dokusu ile Halkalı ve Atakent'teki yeni siteler bir arada.",
  "boru":"Sefaköy ve Cennet tarafındaki eski binalarda galvaniz kolonlar, Halkalı'daki sitelerde ise ankastre plastik tesisat var.",
  "gider":"Bodrum katı olan eski binalarda gider geri tepmesi görülebiliyor; önce geri tepmenin bina içinden mi sokak hattından mı geldiğini ayırıyoruz.",
  "isinma":"Bireysel kombi yaygın; Halkalı'daki sitelerde panel petek, eski binalarda döküm ve eski tip petekler hâlâ kullanılıyor.",
  "saha":"İlçe geniş olduğu için mahalle bilgisini baştan alıp ekibi Sefaköy ya da Halkalı tarafından yönlendiriyoruz."},
 {"ad":"Sarıyer","slug":"sariyer",
  "komsu":["besiktas","sisli","kagithane","eyupsultan"],
  "mahalle":["Maslak","Tarabya","Yeniköy","Kilyos","Bahçeköy","Rumelifeneri"],
  "yapi":"Sarıyer'de Boğaz kıyısındaki eski yapılar, bahçeli konutlar, Maslak'taki plazalar ve kuzeyde köy dokusu bir arada.",
  "boru":"Bahçeli ve müstakil evlerde ana hat uzun; kaçak çoğu zaman bahçede ıslak bir alan ya da düşen basınçla fark ediliyor.",
  "gider":"Kuzey köylerinde ve bazı bahçeli evlerde fosseptik kullanımı devam ediyor; tıkanıklık ile fosseptik dolmasını ayırmak gerekiyor.",
  "isinma":"Müstakil evlerde yüksek kapasiteli kombiler ve geniş petek sistemleri yaygın; bazı eski yapılarda kat kaloriferi hâlâ duruyor.",
  "saha":"Dik rampalarda aracın yanaşamadığı adreslere taşınabilir ekipmanla çıkıyoruz."},
 {"ad":"Silivri","slug":"silivri",
  "komsu":["buyukcekmece","catalca"],
  "mahalle":["Selimpaşa","Gümüşyaka","Ortaköy","Alipaşa","Değirmenköy","Kavaklı"],
  "yapi":"Silivri'de sahil yazlıkları, köy evleri ve yıl boyu oturulan siteler bir arada.",
  "boru":"Kışın boş kalan yazlıklarda donan hatlar ve kuruyan contalar sezon açılışında sızıntı olarak ortaya çıkıyor.",
  "gider":"Yazlık sitelerde sezon başında uzun süre kullanılmayan giderlerde koku ve tıkanıklık sık görülüyor.",
  "isinma":"Merkezde ve sitelerde kombi yaygın; köylerde ise doğalgaz olmayan evlerde farklı ısıtma sistemleri kullanılıyor.",
  "saha":"Mesafe uzun olduğu için Silivri'deki işleri aynı güzergâhta toplayıp günü baştan planlıyoruz."},
 {"ad":"Sultangazi","slug":"sultangazi",
  "komsu":["gaziosmanpasa","esenler","basaksehir","eyupsultan","arnavutkoy"],
  "mahalle":["Cebeci","Habibler","Uğur Mumcu","Esentepe","Gazi","50. Yıl"],
  "yapi":"Sultangazi'de dönüşüm süreci devam eden yoğun konut alanları ağırlıkta.",
  "boru":"Kat ilavesi yapılmış binalarda üst katlara giden hat sonradan uzatıldığı için basınç düşüklüğü ve bağlantı kaçağı sık.",
  "gider":"Hat güzergâhının belli olmadığı eski binalarda tıkanıklığın yerini önce kamerayla buluyoruz.",
  "isinma":"Daire başı kombi yaygın; sonradan eklenen katlarda petek hattının dengesiz olması bazı odaların ısınmamasına neden oluyor.",
  "saha":"Mahalle ve sokak bilgisini telefonda netleştirip ekibi en kısa güzergâhtan yönlendiriyoruz."},
 {"ad":"Şişli","slug":"sisli",
  "komsu":["besiktas","beyoglu","kagithane","sariyer","eyupsultan"],
  "mahalle":["Nişantaşı","Mecidiyeköy","Kurtuluş","Fulya","Bomonti","Esentepe"],
  "yapi":"Şişli'de plaza ve iş merkezleri ile Kurtuluş–Nişantaşı tarafındaki eski apartmanlar bir arada.",
  "boru":"Kurtuluş ve Nişantaşı'ndaki eski apartmanlarda tesisat yüzyılın ortasından kalma olabiliyor; kolon değişimi ertelenmiş binalar çok.",
  "gider":"Eski apartmanların döküm gider hatları içten daralmış; plazalarda ise mutfak ve WC hatlarının yoğun kullanımı tıkanıklık yapıyor.",
  "isinma":"Eski apartmanların bir bölümü hâlâ merkezi sistemle ısınıyor; bireysel kombiye geçen dairelerde eski petekler korunmuş.",
  "saha":"Plazalarda teknik müdürlükten çalışma iznini alarak, apartmanlarda yöneticiyle konuşarak giriyoruz."},
 {"ad":"Zeytinburnu","slug":"zeytinburnu",
  "komsu":["fatih","bakirkoy","gungoren","bayrampasa"],
  "mahalle":["Merkezefendi","Telsiz","Seyitnizam","Kazlıçeşme","Yenidoğan","Veliefendi"],
  "yapi":"Zeytinburnu'nda deri ve tekstil sanayisinden dönüşen bölgelerle yoğun konut alanları iç içe.",
  "boru":"Eski konutlarda galvaniz tesisat hâlâ yaygın; dönüşen bölgelerde ise yeni binaların tesisatı tamamen farklı.",
  "gider":"İş yeri kullanımı olan binalarda ortak gider hattı yoğun yükleniyor; sahile yakın düşük kotlu yerlerde geri tepme görülebiliyor.",
  "isinma":"Bireysel kombi yaygın; eski binalarda sonradan çekilen petek hatları dengesiz çalışabiliyor.",
  "saha":"Sahil ve iç kesim için ayrı güzergâh planlıyor, mahalleyi baştan öğreniyoruz."},
]


# ── Hizmetler ───────────────────────────────────────────────────────────────
# ilce=True → 25 ilçe sayfası açılır. "alan" = ilçe metninde hangi ilçe alanının kullanılacağı.
# "es" = aynı niyetin eş anlamlıları; ⛔ bunlar için AYRI SAYFA AÇILMAZ (kannibalizasyon).
HIZMETLER = [
 {"slug":"su-tesisatcisi","ad":"Su Tesisatçısı","kisa":"Su tesisatı","ilce":True,
  "h1":"{ad} Su Tesisatçısı","title":"{ad} Su Tesisatçısı | Tesisat Ustası 7/24",
  "alan":["boru"],"gorsel":"tesisat",
  "es":["tesisat ustası","tesisatçı","su tesisatı ustası","acil tesisatçı"],
  "ozet":"Musluk, batarya, vana, boru patlağı ve tesisat yenileme işleri için usta gönderiyoruz.",
  "isler":[
   ("Boru patlağı ve acil müdahale","Patlayan ya da çatlayan boruda önce suyu kesip hasarı durduruyor, sonra kalıcı onarımı yapıyoruz."),
   ("Musluk ve batarya","Damlatan musluk, değişecek batarya, ankastre ya da mutfak bataryası montajı."),
   ("Vana ve rakor","Ana vana, kombi altı vanaları, kollektör vanaları ve sızdıran rakor değişimi."),
   ("Klozet ve rezervuar","Su kaçıran rezervuar takımı, gömme rezervuar arızası, klozet montajı."),
   ("Tesisat yenileme","Paslanan galvaniz hattın plastik esaslı borularla yenilenmesi, daire içi tesisat değişimi."),
   ("Basınç sorunları","Düşük basınç, hidrofor ve basınç düşürücü ayarı, tıkanan filtre ve perlatör temizliği."),
  ],
  "belirti":[
   "Bir yerden sürekli damlama ya da tıslama sesi geliyor",
   "Su faturası kullanımınıza göre beklenmedik şekilde arttı",
   "Musluklardan gelen suyun basıncı düştü ya da kesik kesik akıyor",
   "Alt kattaki komşunun tavanında leke oluştu",
   "Vanayı kapattığınız hâlde su tam kesilmiyor",
   "Rezervuar sürekli su dolduruyor ya da klozete su sızdırıyor",
   "Boru üzerinde pas, yeşillenme ya da nem izi görüyorsunuz",
  ],
  "oneri":[
   "Su akıyorsa önce daire ana vanasını kapatın; genellikle sayacın yanında ya da mutfak tezgâhının altında olur.",
   "Su elektrik prizine ya da sigorta kutusuna yaklaşıyorsa ilgili sigortayı indirin.",
   "Akan suyu kova ve havluyla toplayın; alt kattaki komşuya haber verin.",
   "Kaçak noktasının fotoğrafını çekip WhatsApp'tan gönderin; usta gelmeden önce hangi parçanın gerektiğini görebiliriz.",
  ],
  "sss":[
   ("{ad}{loc} su tesisatçısı ne kadar sürede gelir?","Ekiplerimiz Avrupa yakasında ortalama 30 dakikada adrese ulaşıyor. Trafik ve o anki iş yoğunluğuna göre süre değişebilir; arama sırasında size tahmini süreyi söylüyoruz."),
   ("Gece ya da hafta sonu tesisatçı gelir mi?","Evet. 7/24 hizmet veriyoruz; gece yarısı patlayan bir boru için de, pazar günü damlayan bir musluk için de arayabilirsiniz."),
   ("Tesisat ustası gelmeden fiyat söyleyebilir misiniz?","Fotoğraf ya da kısa bir videoyla işin kapsamını görebilirsek yaklaşık bilgi veriyoruz. Kesin fiyatı usta yerinde baktıktan sonra, işe başlamadan önce söylüyor."),
   ("Tesisatçı ile su kaçağı tespiti aynı iş mi?","Hayır. Görünen bir arızayı tesisatçı onarır; kaynağı görünmeyen kaçak için önce cihazla tespit yapılır. İkisini de biz yapıyoruz."),
   ("Malzemeyi siz mi getiriyorsunuz?","Sık kullanılan vana, rakor, batarya ve boru parçaları araçta bulunuyor. Özel bir model istiyorsanız önceden haber verin."),
  ]},

 {"slug":"tikaniklik-acma","ad":"Tıkanıklık ve Gider Açma","kisa":"Tıkanıklık açma","ilce":True,
  "h1":"{ad} Tıkanıklık ve Gider Açma","title":"{ad} Tıkanıklık Açma ve Gider Açma | 7/24",
  "alan":["gider"],"gorsel":"tesisat",
  "es":["gider açma","tıkalı gider açma","lavabo tıkanıklığı açma","tuvalet tıkanıklığı açma","kanal açma"],
  "ozet":"Lavabo, tuvalet, banyo, mutfak gideri ve ana hat tıkanıklıklarını kırmadan açıyoruz.",
  "isler":[
   ("Lavabo ve mutfak gideri","Yağ, sabun ve kireç birikimiyle tıkanan lavabo ve evye giderlerinin açılması."),
   ("Tuvalet ve klozet","Klozet ve tuvalet giderindeki tıkanıklığın kırmadan açılması."),
   ("Banyo ve duş gideri","Saç ve sabun birikimiyle yavaşlayan ya da tamamen tıkanan duş ve küvet giderleri."),
   ("Ana hat ve kolon","Birden fazla daireyi etkileyen bina kolon ve ana gider hattı tıkanıklıkları."),
   ("Kameralı tespit","Tekrarlayan tıkanıklıkta hattın içini kamerayla görüp sebebi ve yeri belirleme."),
   ("Rögar ve bahçe hattı","Bina ile sokak hattı arasındaki rögar ve dış gider hattının açılması."),
  ],
  "belirti":[
   "Lavabo ya da duş suyu geç gidiyor",
   "Giderden fokurdama sesi geliyor",
   "Tuvaletin sifonu çekilince su yükseliyor",
   "Banyoda ya da mutfakta kötü koku var",
   "Bir giderde su boşaltınca başka bir giderden su çıkıyor",
   "Alt katlarda ya da bodrumda giderden su geri geliyor",
   "Aynı gider kısa aralıklarla tekrar tıkanıyor",
  ],
  "oneri":[
   "Tıkalı gidere su dökmeye devam etmeyin; seviye yükselirse taşma riski artar.",
   "Tuz ruhu, kostik gibi kimyasalları karıştırarak kullanmayın; zehirli gaz çıkarabilir ve geri püskürebilir.",
   "Birden fazla giderde sorun varsa sorun ortak hatta olabilir; komşulara da sorun.",
   "Çamaşır ve bulaşık makinesini tıkanıklık açılana kadar çalıştırmayın.",
  ],
  "sss":[
   ("{ad}{loc} gider açma ne kadar sürer?","Lavabo ve duş giderleri çoğu zaman kısa sürede açılıyor. Ana hat ya da tekrarlayan tıkanıklıkta önce sebebi bulmak gerektiği için süre uzayabilir."),
   ("Tıkanıklık açarken fayans kırılır mı?","Hayır, tıkanıklık açmada kırma gerekmez. Spiral ve basınçlı su gibi yöntemlerle giderin içinden çalışıyoruz."),
   ("Tıkanıklık açma ile gider açma aynı şey mi?","Evet, ikisi aynı hizmetin farklı adları. Lavabo, tuvalet, banyo ve mutfak giderlerinin hepsi bu kapsamda."),
   ("Tıkanıklık sürekli tekrarlıyorsa ne yapılmalı?","Tekrarlayan tıkanıklık genellikle hattın içinde bir daralma, kırık ya da yanlış eğim olduğunu gösterir. Bu durumda kamerayla hattın içine bakıp sebebi gösteriyoruz."),
   ("Gece tuvalet tıkanırsa gelir misiniz?","Evet, 7/24 hizmet veriyoruz. Tuvalet tıkanıklığı beklemeye gelmeyen işlerden biri."),
  ]},

 {"slug":"su-kacagi-tespiti","ad":"Su Kaçağı Tespiti","kisa":"Su kaçağı tespiti","ilce":True,
  "h1":"{ad} Su Kaçağı Tespiti","title":"{ad} Su Kaçağı Tespiti | Kırmadan Cihazla",
  "alan":["boru","yapi"],"gorsel":"tesisat",
  "es":["kırmadan su kaçağı tespiti","cihazla su kaçağı bulma","su sızıntısı tespiti"],
  "ozet":"Kaynağı görünmeyen su kaçağını cihazla, kırmadan buluyor ve noktasal onarıyoruz.",
  "isler":[
   ("Cihazla tespit","Akustik dinleme, basınç testi ve termal görüntüleme gibi yöntemlerle kaçağın yerini kırmadan belirleme."),
   ("Noktasal onarım","Kaçak bulunduktan sonra yalnızca o noktayı açıp onarma; bütün banyoyu kırmadan."),
   ("Tavan ve duvar lekesi","Komşu tavanında ya da duvarda oluşan nem lekesinin hangi hattan geldiğini ayırma."),
   ("Yüksek fatura","Görünür bir sızıntı yokken artan su faturasının nedenini sayaç ve basınç testiyle bulma."),
   ("Yerden ısıtma kaçağı","Yerden ısıtma devrelerinde ve kombi tesisatında basınç kaybının kaynağını belirleme."),
  ],
  "belirti":[
   "Su faturası kullanımınız artmadan yükseldi",
   "Tüm musluklar kapalıyken su sayacı dönüyor",
   "Duvarda kabaran boya, fayans derzinde kararma var",
   "Alt kattaki komşunun tavanında leke oluştu",
   "Kombinin basıncı sık sık düşüyor",
   "Zeminde nedeni bilinmeyen ıslaklık ya da sıcak bölge var",
  ],
  "oneri":[
   "Tüm muslukları kapatıp sayaca bakın; dönüyorsa kaçak büyük ihtimalle tesisatta.",
   "Leke büyüyorsa daire ana vanasını kapatın ve elektrik prizlerinden uzak tutun.",
   "Lekenin ve sayacın fotoğrafını tarihleriyle saklayın; komşu ve yönetimle görüşmede işinize yarar.",
  ],
  "sss":[
   ("{ad}{loc} kırmadan su kaçağı tespiti nasıl yapılıyor?","Önce tesisatı bölümlere ayırıp basınç testiyle kaçağın hangi hatta olduğunu buluyoruz. Sonra cihazla dinleyerek ve görüntüleyerek noktayı daraltıyoruz. Yalnızca kaçağın olduğu yer açılıyor."),
   ("Su kaçağı bulunduktan sonra tamiri de yapıyor musunuz?","Evet. Kaçağın yerini bulduktan sonra o noktayı açıp onarıyor, yüzeyi kapatıyoruz."),
   ("Komşumun tavanında leke var, kaçak bende mi?","Her zaman değil. Leke üst daireden, bina kolonundan ya da çatıdan da gelebilir. Tespit bu ayrımı yapmak için gerekli."),
   ("Kombinin basıncı düşüyorsa su kaçağı mı vardır?","Olabilir. Petek ya da yerden ısıtma hattındaki küçük bir kaçak basıncı düşürür. Kombinin emniyet ventilinden su atması da benzer belirti verir; ikisini ayırıyoruz."),
  ]},

 {"slug":"petek-temizleme","ad":"Petek Temizleme","kisa":"Petek temizleme","ilce":True,
  "h1":"{ad} Petek Temizleme","title":"{ad} Petek Temizleme | Makineyle Petek Yıkama",
  "alan":["isinma"],"gorsel":"petek",
  "es":["kalorifer peteği temizleme","petek yıkama","makineli petek temizleme"],
  "ozet":"Isınmayan, altı soğuk kalan peteklerdeki çamur ve tortuyu makineyle temizliyoruz.",
  "isler":[
   ("Makineyle petek temizliği","Petek tesisatının makineye bağlanıp temizlik solüsyonuyla devridaim edilerek çamur ve tortudan arındırılması."),
   ("Hava alma ve dengeleme","Temizlik sonrası peteklerin havasının alınması ve odalar arası ısı dengesinin ayarlanması."),
   ("Termostatik vana","Petek vanası ve termostatik vana montajı ya da değişimi."),
   ("Petek sökme ve takma","Boya, tadilat ya da yer değişikliği için peteğin sökülüp yeniden bağlanması."),
   ("Kaçak ve damlama","Petek rakoru ve vanasındaki damlamaların giderilmesi."),
  ],
  "belirti":[
   "Peteğin üstü sıcak, altı soğuk kalıyor",
   "Bazı odalar ısınırken bazıları soğuk kalıyor",
   "Kombi sürekli çalışmasına rağmen ev geç ısınıyor",
   "Peteklerden ya da tesisattan şırıltı, tıkırtı sesi geliyor",
   "Peteğin havasını alınca siyah, çamurlu su geliyor",
   "Doğalgaz faturası geçen yıla göre belirgin şekilde arttı",
  ],
  "oneri":[
   "Petek temizliği öncesinde petek önlerindeki eşyaları biraz uzaklaştırın.",
   "Kombinin basıncını not edin; temizlikten sonra karşılaştırmak işinize yarar.",
   "Isıtma sezonu başlamadan, sonbaharda yaptırmak hem kuyruğu hem de soğukta kalma riskini azaltır.",
  ],
  "sss":[
   ("{ad}{loc} petek temizleme ne kadar sürer?","Daire büyüklüğüne ve petek sayısına göre değişmekle birlikte genellikle birkaç saat sürüyor. Temizlik bittiğinde petekleri çalıştırıp ısınmayı birlikte kontrol ediyoruz."),
   ("Petek temizliği ne sıklıkla yapılmalı?","Sistemin yaşına ve suyun durumuna göre değişir. Peteğin altı soğuk kalıyorsa ya da hava alırken çamurlu su geliyorsa zamanı gelmiş demektir."),
   ("Petek temizliği için petekleri sökmek gerekiyor mu?","Hayır. Makineli temizlikte petekler yerinde kalır; tesisat makineye bağlanıp temizlenir."),
   ("Petek temizliği doğalgaz faturasını düşürür mü?","Çamurla tıkanan petek ısıyı odaya veremediği için kombi daha uzun çalışır. Temizlik ısınma verimini artırır; faturadaki etki evin yalıtımına ve kullanıma göre değişir."),
  ]},

 {"slug":"kombi-servisi","ad":"Kombi Servisi","kisa":"Kombi servisi","ilce":True,
  "h1":"{ad} Kombi Servisi","title":"{ad} Kombi Servisi | Kombi Tamiri ve Bakımı",
  "alan":["isinma"],"gorsel":"petek",
  "es":["kombi tamiri","kombi bakımı","kombi tamircisi","kombi arıza"],
  "ozet":"Kombi arızası, yıllık bakım, basınç ve sıcak su sorunları için servis veriyoruz.",
  "isler":[
   ("Arıza tespiti ve onarım","Kombinin hata kodu ve belirtilerine göre arızanın tespit edilip onarılması."),
   ("Yıllık kombi bakımı","Brülör, eşanjör ve fan kontrolü, temizlik ve emniyet ayarlarının kontrolü."),
   ("Basınç sorunları","Sürekli düşen ya da yükselen basıncın sebebinin bulunması; genleşme tankı kontrolü."),
   ("Sıcak su sorunu","Sıcak suyun gelmemesi, ılık gelmesi ya da sıcaklığın dalgalanması."),
   ("Parça değişimi","Arızalı pompa, sensör, vana ve benzeri parçaların değiştirilmesi."),
  ],
  "belirti":[
   "Kombi ekranında hata kodu görünüyor",
   "Kombi basıncı sürekli düşüyor ya da çok yükseliyor",
   "Sıcak su gelmiyor ya da ılık geliyor",
   "Kombi sık sık kapanıp açılıyor",
   "Kombiden alışılmadık ses geliyor",
   "Kombinin altından su damlıyor",
  ],
  "oneri":[
   "Gaz kokusu alıyorsanız kombiyi ve elektrik düğmelerini çalıştırmayın, pencereleri açın, gaz vanasını kapatın ve 187 Doğalgaz Acil'i arayın.",
   "Ekrandaki hata kodunu ve kombinin marka-modelini not edin; fotoğrafını WhatsApp'tan gönderin.",
   "Basınç düştüyse kombi doldurma musluğuyla 1,5 bar civarına getirmeyi deneyebilirsiniz; tekrar düşüyorsa kaçak olabilir.",
  ],
  "sss":[
   ("{ad}{loc} kombi servisi aynı gün gelir mi?","Evet, 7/24 hizmet veriyoruz. Ekiplerimiz Avrupa yakasında ortalama 30 dakikada adrese ulaşıyor."),
   ("Yetkili servis misiniz?","Hayır. Armin Tesisat herhangi bir kombi markasının yetkili servisi değildir; farklı marka ve modellerde bağımsız servis olarak arıza tespiti, bakım ve onarım yapıyoruz. Garanti süresi devam eden kombilerde önce markanın yetkili servisine başvurmanızı öneririz."),
   ("Kombi bakımı ne zaman yapılmalı?","Isıtma sezonu başlamadan önce, sonbaharda yapılması önerilir. Bakımsız kombide hem verim düşer hem de arıza ihtimali artar."),
   ("Gaz kokusu varsa sizi mi aramalıyım?","Hayır. Gaz kokusunda önce 187 Doğalgaz Acil'i arayın, cihazları ve elektrik düğmelerini kullanmayın. Gaz hattı ve doğalgaz projesi işleri İGDAŞ yetkili firmalarınca yapılır."),
  ]},

 {"slug":"elektrikci","ad":"Elektrikçi","kisa":"Elektrik","ilce":False,
  "h1":"Elektrikçi — İstanbul Avrupa Yakası","title":"Elektrikçi İstanbul Avrupa Yakası | Elektrik Arıza 7/24",
  "alan":[],"gorsel":"elektrik",
  "es":["elektrik ustası","elektrik arıza"],
  "ozet":"Elektrik arıza tespiti, priz-anahtar, aydınlatma ve pano işleri.",
  "isler":[
   ("Arıza tespiti","Sigortanın atması, kaçak akım rölesinin düşmesi, elektriğin bir bölümde kesilmesi gibi arızaların tespiti ve onarımı."),
   ("Priz ve anahtar","Priz, anahtar ve topraklı priz montajı ile değişimi."),
   ("Aydınlatma","Avize, spot ve aydınlatma hattı montajı."),
   ("Pano bakımı","Sigorta panosunun kontrolü, sigorta ve kaçak akım rölesi değişimi."),
  ],
  "belirti":[
   "Sigorta sık sık atıyor",
   "Kaçak akım rölesi düşüyor",
   "Prizden kıvılcım ya da yanık kokusu geliyor",
   "Evin bir bölümünde elektrik yok",
  ],
  "oneri":[
   "Yanık kokusu ya da kıvılcım varsa ilgili sigortayı indirin ve o prizi kullanmayın.",
   "Islak elle priz ve anahtara dokunmayın.",
  ],
  "sss":[
   ("Elektrikçi gece gelir mi?","Evet, 7/24 hizmet veriyoruz."),
   ("Kaçak akım rölesi neden sürekli düşer?","Rutubet alan bir priz, arızalı bir cihaz ya da hattaki bir yalıtım sorunu röleyi düşürebilir. Cihazları tek tek ayırarak kaynağı buluyoruz."),
  ]},
]
